### ISSUE TITLE
Robust + Examples

### ISSUE THREAD

**Issue by flrgsr** [luiscarlosgph/t-Student-Mixture-Models#1]
Hi!

I was wondering how robuts/major this project is.
I would need a python implementation to fit a mixture of student-t distributions to samples, giving me the "location", "scale" and "degrees of freedom" parameters.

I just tried running the code on a simple one component model but get the error:

> RuntimeError: EM algorithm was never able to compute a valid likelihood given initial parameters. Try different init parameters (or increasing n_init) or check for degenerate data.

Furthermore I would be grateful if you could include a more comprehensive example (the one provided in the code as comment seems to be broken too).

E.g please correct me if I am wrong: 

```
from sklearn import mixture
np.random.seed(1)
 g = mixture.SMM(n_components=2)

```

This example fails with an error immediately as SMM is not part of sklearn.

Thanks.

**Comment by luiscarlosgph** [comment]
Hi,

Thanks for raising the issue. I have added some unit tests and an example script (src/smm/example.py) for you to test.

Kind Regards,
Luis.
